### ISSUE TITLE
Wrong last seen time in chat history

### ISSUE THREAD

**Issue by webratte** [kontalk/desktopclient-java#82] opened 2016-09-18 10:18 UTC
Kontalk: V 3.1.1
OS: Linux

Last seen should be updated from server like in Android client.
Currently the last seen time seams to be the last sent or received time via Desktop client.
Or what ever. I can't find what's really the shown time.

There are different times in contact list and chat history.

e.g my wife in this moment:

Android client: 27 minutes
Desktop client chat history: 1 month
Desktop client contact list: 21 houres

It's really strange ;-)

**Comment by abika** [comment] 2016-09-18 12:30
The desktop client shows two different timestamps:
* last activity in a chat. Equal to last message sent/received time and consistent with the chat list order.
* last seen for a contact. Should be equal to the time in Android client. If it differs its probably caused by the clients connected at different times (there is no timestamp saved on the server).

A "Last seen" time wouldn't make sense for group chats.

**Comment by abika** [comment] 2016-09-18 12:36
oh wait, there is [XEP-0012](https://xmpp.org/extensions/xep-0012.html). Should use that.

**Comment by webratte** [comment] 2016-09-18 12:39
> there is no timestamp saved on the server

Please help to understand:
I switch off my phone at 9 PM and switch it on at 7 AM
If I take a look to my contacts I can see some of they was online between this time.
So that only can be a information from server.
Isn't it?

**Comment by webratte** [comment] 2016-09-18 12:42
The last activity in a chat is definitely different to Android client for all my contacts.
I'm relative sure it's the time I have sent or received a message from desktopclient to this contact.

**Comment by abika** [comment] 2016-09-18 12:46
> So that only can be a information from server.
> Isn't it?

Yes, XEP-0012. Totally missed that but I will work on it.

> The last activity in a chat is definitely different to Android client for all my contacts.
> I'm relative sure it's the time I have sent or received a message from desktopclient to this contact. 

Yes, it's simply the time the last message was send/received in chat. There is no such time shown in the Android client.

**Comment by webratte** [comment] 2016-09-18 12:50
> Yes, XEP-0012. Totally missed that but I will work on it.

You was faster by answering then I by asking ;-)

> Yes, it's simply the time the last message was send/received in chat. There is no such time shown in the Android client.

Maybe you should move this information to the chatballoon to make it more like in Android client. You see, it can be confusing for stupid users like me ;-)

**Comment by webratte** [comment] 2016-09-18 12:55
Also for other things, I think the look and feel should more similar to the android client to make using of both clients more intuitive.

**Comment by Buranek** [comment] 2016-09-21 13:13
I agree with @webratte.

**Comment by abika** [comment] 2016-09-21 13:56
@webratte XEP-0012 is implemented. The "last_seen" timestamp should be a lot more precise now.

@daniele-athome Basically on every (re-)connection I have to request the last_seen time for every (offline) contact. It feels like a lot of traffic for such a small information but there is no other way, right?

@webratte 
> Maybe you should move this information to the chatballoon to make it more like in Android client. You see, it can be confusing for stupid users like me ;-)
Actually there is a similar time for the last chat activity shown in the Android client: A date (e.g. "Sep 19") on the right side in the chat list. What you mean with "chatballoon"? The best way to prevent confusion is to remove this date in the chat list of the desktop client. But I don't like that either.

@webratte @Buranek 
There are tons of potential improvements for the UI. Most are small things that can still need a lot of implementation time. I'll make a list and open another issue.

**Comment by webratte** [comment] 2016-09-21 14:03
Actually there is a similar time for the last chat activity shown in the Android client: A date (e.g. "Sep 19") on the right side in the chat list. What you mean with "chatballoon"? 

@abika exactly that. 
"A date (e.g. "Sep 19") on the right side in the chat list."

Chatballoon was the wrong term. Sorry, my mistake.

**Comment by abika** [comment] 2016-09-21 14:10
How about this: switch the date with the one shown in the tooltip?
* In the chat list: "Mon, Sep 19"
* In the tooltip: "Last activity: Two days ago"

**Comment by daniele-athome** [comment] 2016-09-21 14:38
@abika I think a "last activity" as in last message received (if I understood you correctly) is confusing for users coming from Android. Maybe you could change the label into "Last message"?

As for XEP-0012, unfortunately there is no other way besides requesting all of them at connect time, since it's IQ-based.

**Comment by Buranek** [comment] 2016-09-21 15:25
Last online — is the time when user was online last time.
Last message — is the time when you have sent a message to this user or this user has sent a message to  you.

**Comment by abika** [comment] 2016-09-21 15:36
Well, then "last message" instead of "last activity". But I will keep "last seen", the difference to "last online" is really small.

**Comment by abika** [comment] 2016-09-24 16:34
XEP-0012 implemented and tooltip string changed. Will close this for now

**Closed by abika** 2016-09-24 16:34 UTC
